# Site settings
title: XHP-Lib
description: > # this means to ignore newlines until "baseurl:"
  XHP-Lib provides a set of base classes for XHP, a PHP5 extension and part of
  the Hack language which provides a safe way to construct markup by embedding
  an XML-like syntax inside your PHP/Hack code.
baseurl: /xhp-lib # the subpath of your site, e.g. /blog/
github_username: hhvm
twitter_username: HipHopVM
